defaults: &defaults
  lastfm:
    apikey: <%= ENV['LASTFM_KEY'] %>
    secret: <%= ENV['LASTFM_SECRET'] %>

development:
  <<: *defaults

production:
  <<: *defaults

test: &test
  <<: *defaults

cucumber:
  <<: *test
